
export const CATEGORIES = [
  { id: 'fresh-flowers', name: 'Fresh Flowers', image: '/assets/products/fresh-flowers.jpg' },
  { id: 'bouquets', name: 'Flower Bouquets', image: '/assets/products/bouquets.jpg' },
  { id: 'plants', name: 'Flower Plants', image: '/assets/products/plants.jpg' },
  { id: 'seeds', name: 'Flower Seeds', image: '/assets/products/seeds.jpg' },
  { id: 'decor', name: 'Decoration Flowers', image: '/assets/products/decor.jpg' },
  { id: 'gift-combos', name: 'Gift Combos', image: '/assets/products/gift-combos.jpg' }
];

export const MOCK_PRODUCTS = [
  
  {
    id: 'fresh-flowers-0',
    name: 'Crimson Rose',
    slug: 'crimson-rose',
    shortDesc: 'Premium hand-picked Crimson Rose directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Crimson Rose. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'fresh-flowers',
    price: 599,
    discount: 17,
    rating: 4.6,
    reviews: 119,
    stock: 23,
    sku: 'FRE-1000',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: true,
    image: '/assets/products/fresh-flowers-0.jpg'
  },
  {
    id: 'fresh-flowers-1',
    name: 'White Lily',
    slug: 'white-lily',
    shortDesc: 'Premium hand-picked White Lily directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke White Lily. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'fresh-flowers',
    price: 654,
    discount: 0,
    rating: 4.5,
    reviews: 267,
    stock: 51,
    sku: 'FRE-1001',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: true,
    bestSeller: false,
    image: '/assets/products/fresh-flowers-1.jpg'
  },
  {
    id: 'fresh-flowers-2',
    name: 'Sacred Lotus',
    slug: 'sacred-lotus',
    shortDesc: 'Premium hand-picked Sacred Lotus directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Sacred Lotus. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'fresh-flowers',
    price: 871,
    discount: 0,
    rating: 4.8,
    reviews: 102,
    stock: 9,
    sku: 'FRE-1002',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/fresh-flowers-2.jpg'
  },
  {
    id: 'fresh-flowers-3',
    name: 'Dutch Tulip',
    slug: 'dutch-tulip',
    shortDesc: 'Premium hand-picked Dutch Tulip directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Dutch Tulip. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'fresh-flowers',
    price: 1034,
    discount: 0,
    rating: 4.5,
    reviews: 109,
    stock: 11,
    sku: 'FRE-1003',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/fresh-flowers-3.jpg'
  },
  {
    id: 'fresh-flowers-4',
    name: 'Purple Orchid',
    slug: 'purple-orchid',
    shortDesc: 'Premium hand-picked Purple Orchid directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Purple Orchid. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'fresh-flowers',
    price: 1003,
    discount: 14,
    rating: 4.6,
    reviews: 188,
    stock: 42,
    sku: 'FRE-1004',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/fresh-flowers-4.jpg'
  },
  {
    id: 'fresh-flowers-5',
    name: 'Golden Sunflower',
    slug: 'golden-sunflower',
    shortDesc: 'Premium hand-picked Golden Sunflower directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Golden Sunflower. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'fresh-flowers',
    price: 1814,
    discount: 0,
    rating: 4.7,
    reviews: 157,
    stock: 43,
    sku: 'FRE-1005',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/fresh-flowers-5.jpg'
  },
  {
    id: 'fresh-flowers-6',
    name: 'Night Jasmine',
    slug: 'night-jasmine',
    shortDesc: 'Premium hand-picked Night Jasmine directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Night Jasmine. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'fresh-flowers',
    price: 1805,
    discount: 0,
    rating: 4.9,
    reviews: 92,
    stock: 27,
    sku: 'FRE-1006',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/fresh-flowers-6.jpg'
  },
  {
    id: 'fresh-flowers-7',
    name: 'Indian Marigold',
    slug: 'indian-marigold',
    shortDesc: 'Premium hand-picked Indian Marigold directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Indian Marigold. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'fresh-flowers',
    price: 1236,
    discount: 0,
    rating: 4.6,
    reviews: 192,
    stock: 31,
    sku: 'FRE-1007',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/fresh-flowers-7.jpg'
  },
  {
    id: 'fresh-flowers-8',
    name: 'French Lavender',
    slug: 'french-lavender',
    shortDesc: 'Premium hand-picked French Lavender directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke French Lavender. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'fresh-flowers',
    price: 2191,
    discount: 6,
    rating: 4.5,
    reviews: 329,
    stock: 24,
    sku: 'FRE-1008',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/fresh-flowers-8.jpg'
  },
  {
    id: 'fresh-flowers-9',
    name: 'Pink Carnation',
    slug: 'pink-carnation',
    shortDesc: 'Premium hand-picked Pink Carnation directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Pink Carnation. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'fresh-flowers',
    price: 2615,
    discount: 0,
    rating: 4.9,
    reviews: 147,
    stock: 21,
    sku: 'FRE-1009',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/fresh-flowers-9.jpg'
  },
  {
    id: 'fresh-flowers-10',
    name: 'Blue Hydrangea',
    slug: 'blue-hydrangea',
    shortDesc: 'Premium hand-picked Blue Hydrangea directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Blue Hydrangea. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'fresh-flowers',
    price: 2699,
    discount: 0,
    rating: 4.9,
    reviews: 284,
    stock: 42,
    sku: 'FRE-1010',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/fresh-flowers-10.jpg'
  },
  {
    id: 'fresh-flowers-11',
    name: 'Yellow Daffodil',
    slug: 'yellow-daffodil',
    shortDesc: 'Premium hand-picked Yellow Daffodil directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Yellow Daffodil. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'fresh-flowers',
    price: 2975,
    discount: 0,
    rating: 4.8,
    reviews: 119,
    stock: 9,
    sku: 'FRE-1011',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/fresh-flowers-11.jpg'
  },
  {
    id: 'fresh-flowers-12',
    name: 'Red Hibiscus',
    slug: 'red-hibiscus',
    shortDesc: 'Premium hand-picked Red Hibiscus directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Red Hibiscus. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'fresh-flowers',
    price: 2759,
    discount: 16,
    rating: 4.7,
    reviews: 274,
    stock: 8,
    sku: 'FRE-1012',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/fresh-flowers-12.jpg'
  },
  {
    id: 'fresh-flowers-13',
    name: 'White Daisy',
    slug: 'white-daisy',
    shortDesc: 'Premium hand-picked White Daisy directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke White Daisy. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'fresh-flowers',
    price: 3628,
    discount: 0,
    rating: 4.9,
    reviews: 175,
    stock: 18,
    sku: 'FRE-1013',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/fresh-flowers-13.jpg'
  },
  {
    id: 'fresh-flowers-14',
    name: 'Peach Blossom',
    slug: 'peach-blossom',
    shortDesc: 'Premium hand-picked Peach Blossom directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Peach Blossom. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'fresh-flowers',
    price: 2447,
    discount: 0,
    rating: 4.7,
    reviews: 280,
    stock: 37,
    sku: 'FRE-1014',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/fresh-flowers-14.jpg'
  },
  
  {
    id: 'bouquets-0',
    name: 'Royal Birthday Bouquet',
    slug: 'royal-birthday-bouquet',
    shortDesc: 'Premium hand-picked Royal Birthday Bouquet directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Royal Birthday Bouquet. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'bouquets',
    price: 1499,
    discount: 7,
    rating: 4.9,
    reviews: 117,
    stock: 10,
    sku: 'BOU-2000',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: true,
    image: '/assets/products/bouquets-0.jpg'
  },
  {
    id: 'bouquets-1',
    name: 'Elegance Wedding Bouquet',
    slug: 'elegance-wedding-bouquet',
    shortDesc: 'Premium hand-picked Elegance Wedding Bouquet directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Elegance Wedding Bouquet. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'bouquets',
    price: 1625,
    discount: 0,
    rating: 4.6,
    reviews: 110,
    stock: 14,
    sku: 'BOU-2001',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: true,
    bestSeller: false,
    image: '/assets/products/bouquets-1.jpg'
  },
  {
    id: 'bouquets-2',
    name: 'Silver Anniversary Bouquet',
    slug: 'silver-anniversary-bouquet',
    shortDesc: 'Premium hand-picked Silver Anniversary Bouquet directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Silver Anniversary Bouquet. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'bouquets',
    price: 1903,
    discount: 0,
    rating: 4.9,
    reviews: 55,
    stock: 14,
    sku: 'BOU-2002',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/bouquets-2.jpg'
  },
  {
    id: 'bouquets-3',
    name: 'Midnight Romance Bouquet',
    slug: 'midnight-romance-bouquet',
    shortDesc: 'Premium hand-picked Midnight Romance Bouquet directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Midnight Romance Bouquet. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'bouquets',
    price: 1901,
    discount: 0,
    rating: 4.8,
    reviews: 136,
    stock: 27,
    sku: 'BOU-2003',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/bouquets-3.jpg'
  },
  {
    id: 'bouquets-4',
    name: '100 Luxury Roses',
    slug: '100-luxury-roses',
    shortDesc: 'Premium hand-picked 100 Luxury Roses directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke 100 Luxury Roses. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'bouquets',
    price: 2431,
    discount: 16,
    rating: 4.6,
    reviews: 335,
    stock: 6,
    sku: 'BOU-2004',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/bouquets-4.jpg'
  },
  {
    id: 'bouquets-5',
    name: 'Exotic Mix Bouquet',
    slug: 'exotic-mix-bouquet',
    shortDesc: 'Premium hand-picked Exotic Mix Bouquet directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Exotic Mix Bouquet. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'bouquets',
    price: 2589,
    discount: 0,
    rating: 4.6,
    reviews: 287,
    stock: 52,
    sku: 'BOU-2005',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/bouquets-5.jpg'
  },
  {
    id: 'bouquets-6',
    name: 'Purity White Bouquet',
    slug: 'purity-white-bouquet',
    shortDesc: 'Premium hand-picked Purity White Bouquet directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Purity White Bouquet. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'bouquets',
    price: 2963,
    discount: 0,
    rating: 4.7,
    reviews: 283,
    stock: 47,
    sku: 'BOU-2006',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/bouquets-6.jpg'
  },
  {
    id: 'bouquets-7',
    name: 'Diwali Festival Bouquet',
    slug: 'diwali-festival-bouquet',
    shortDesc: 'Premium hand-picked Diwali Festival Bouquet directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Diwali Festival Bouquet. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'bouquets',
    price: 3088,
    discount: 0,
    rating: 4.6,
    reviews: 70,
    stock: 43,
    sku: 'BOU-2007',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/bouquets-7.jpg'
  },
  {
    id: 'bouquets-8',
    name: 'Mothers Love Bouquet',
    slug: 'mothers-love-bouquet',
    shortDesc: 'Premium hand-picked Mothers Love Bouquet directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Mothers Love Bouquet. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'bouquets',
    price: 2187,
    discount: 10,
    rating: 4.7,
    reviews: 91,
    stock: 22,
    sku: 'BOU-2008',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/bouquets-8.jpg'
  },
  {
    id: 'bouquets-9',
    name: 'Success Congratulations Bouquet',
    slug: 'success-congratulations-bouquet',
    shortDesc: 'Premium hand-picked Success Congratulations Bouquet directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Success Congratulations Bouquet. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'bouquets',
    price: 3326,
    discount: 0,
    rating: 4.9,
    reviews: 147,
    stock: 5,
    sku: 'BOU-2009',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/bouquets-9.jpg'
  },
  {
    id: 'bouquets-10',
    name: 'Velvet Dreams Bouquet',
    slug: 'velvet-dreams-bouquet',
    shortDesc: 'Premium hand-picked Velvet Dreams Bouquet directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Velvet Dreams Bouquet. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'bouquets',
    price: 3929,
    discount: 0,
    rating: 4.5,
    reviews: 133,
    stock: 7,
    sku: 'BOU-2010',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/bouquets-10.jpg'
  },
  {
    id: 'bouquets-11',
    name: 'Sunrise Glory Bouquet',
    slug: 'sunrise-glory-bouquet',
    shortDesc: 'Premium hand-picked Sunrise Glory Bouquet directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Sunrise Glory Bouquet. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'bouquets',
    price: 3039,
    discount: 0,
    rating: 4.9,
    reviews: 85,
    stock: 31,
    sku: 'BOU-2011',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/bouquets-11.jpg'
  },
  {
    id: 'bouquets-12',
    name: 'Pastel Harmony Bouquet',
    slug: 'pastel-harmony-bouquet',
    shortDesc: 'Premium hand-picked Pastel Harmony Bouquet directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Pastel Harmony Bouquet. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'bouquets',
    price: 4259,
    discount: 13,
    rating: 4.9,
    reviews: 78,
    stock: 30,
    sku: 'BOU-2012',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/bouquets-12.jpg'
  },
  {
    id: 'bouquets-13',
    name: 'Classic Red Bouquet',
    slug: 'classic-red-bouquet',
    shortDesc: 'Premium hand-picked Classic Red Bouquet directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Classic Red Bouquet. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'bouquets',
    price: 2409,
    discount: 0,
    rating: 4.5,
    reviews: 282,
    stock: 43,
    sku: 'BOU-2013',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/bouquets-13.jpg'
  },
  {
    id: 'bouquets-14',
    name: 'Summer Breeze Bouquet',
    slug: 'summer-breeze-bouquet',
    shortDesc: 'Premium hand-picked Summer Breeze Bouquet directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Summer Breeze Bouquet. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'bouquets',
    price: 4117,
    discount: 0,
    rating: 4.9,
    reviews: 290,
    stock: 30,
    sku: 'BOU-2014',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/bouquets-14.jpg'
  },
  
  {
    id: 'plants-0',
    name: 'Miniature Rose Plant',
    slug: 'miniature-rose-plant',
    shortDesc: 'Premium hand-picked Miniature Rose Plant directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Miniature Rose Plant. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'plants',
    price: 899,
    discount: 9,
    rating: 4.9,
    reviews: 165,
    stock: 48,
    sku: 'PLA-3000',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: true,
    image: '/assets/products/plants-0.jpg'
  },
  {
    id: 'plants-1',
    name: 'Trailing Jasmine',
    slug: 'trailing-jasmine',
    shortDesc: 'Premium hand-picked Trailing Jasmine directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Trailing Jasmine. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'plants',
    price: 1147,
    discount: 0,
    rating: 4.7,
    reviews: 335,
    stock: 16,
    sku: 'PLA-3001',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: true,
    bestSeller: false,
    image: '/assets/products/plants-1.jpg'
  },
  {
    id: 'plants-2',
    name: 'Tropical Hibiscus',
    slug: 'tropical-hibiscus',
    shortDesc: 'Premium hand-picked Tropical Hibiscus directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Tropical Hibiscus. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'plants',
    price: 1087,
    discount: 0,
    rating: 4.5,
    reviews: 322,
    stock: 52,
    sku: 'PLA-3002',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/plants-2.jpg'
  },
  {
    id: 'plants-3',
    name: 'Variegated Money Plant',
    slug: 'variegated-money-plant',
    shortDesc: 'Premium hand-picked Variegated Money Plant directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Variegated Money Plant. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'plants',
    price: 1370,
    discount: 0,
    rating: 4.9,
    reviews: 72,
    stock: 17,
    sku: 'PLA-3003',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/plants-3.jpg'
  },
  {
    id: 'plants-4',
    name: 'Phalaenopsis Orchid',
    slug: 'phalaenopsis-orchid',
    shortDesc: 'Premium hand-picked Phalaenopsis Orchid directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Phalaenopsis Orchid. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'plants',
    price: 1747,
    discount: 16,
    rating: 4.7,
    reviews: 56,
    stock: 40,
    sku: 'PLA-3004',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/plants-4.jpg'
  },
  {
    id: 'plants-5',
    name: 'Spathiphyllum Peace Lily',
    slug: 'spathiphyllum-peace-lily',
    shortDesc: 'Premium hand-picked Spathiphyllum Peace Lily directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Spathiphyllum Peace Lily. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'plants',
    price: 1624,
    discount: 0,
    rating: 4.9,
    reviews: 273,
    stock: 45,
    sku: 'PLA-3005',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/plants-5.jpg'
  },
  {
    id: 'plants-6',
    name: 'Sansevieria Snake Plant',
    slug: 'sansevieria-snake-plant',
    shortDesc: 'Premium hand-picked Sansevieria Snake Plant directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Sansevieria Snake Plant. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'plants',
    price: 1337,
    discount: 0,
    rating: 4.9,
    reviews: 252,
    stock: 37,
    sku: 'PLA-3006',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/plants-6.jpg'
  },
  {
    id: 'plants-7',
    name: 'Indoor Areca Palm',
    slug: 'indoor-areca-palm',
    shortDesc: 'Premium hand-picked Indoor Areca Palm directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Indoor Areca Palm. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'plants',
    price: 2586,
    discount: 0,
    rating: 4.8,
    reviews: 73,
    stock: 39,
    sku: 'PLA-3007',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/plants-7.jpg'
  },
  {
    id: 'plants-8',
    name: 'Aromatic Lavender Plant',
    slug: 'aromatic-lavender-plant',
    shortDesc: 'Premium hand-picked Aromatic Lavender Plant directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Aromatic Lavender Plant. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'plants',
    price: 2379,
    discount: 12,
    rating: 4.9,
    reviews: 265,
    stock: 49,
    sku: 'PLA-3008',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/plants-8.jpg'
  },
  {
    id: 'plants-9',
    name: 'Vibrant Bougainvillea',
    slug: 'vibrant-bougainvillea',
    shortDesc: 'Premium hand-picked Vibrant Bougainvillea directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Vibrant Bougainvillea. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'plants',
    price: 2717,
    discount: 0,
    rating: 4.8,
    reviews: 261,
    stock: 51,
    sku: 'PLA-3009',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/plants-9.jpg'
  },
  {
    id: 'plants-10',
    name: 'Ficus Bonsai',
    slug: 'ficus-bonsai',
    shortDesc: 'Premium hand-picked Ficus Bonsai directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Ficus Bonsai. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'plants',
    price: 1579,
    discount: 0,
    rating: 4.6,
    reviews: 175,
    stock: 32,
    sku: 'PLA-3010',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/plants-10.jpg'
  },
  {
    id: 'plants-11',
    name: 'Aloe Vera Plant',
    slug: 'aloe-vera-plant',
    shortDesc: 'Premium hand-picked Aloe Vera Plant directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Aloe Vera Plant. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'plants',
    price: 3517,
    discount: 0,
    rating: 4.6,
    reviews: 187,
    stock: 15,
    sku: 'PLA-3011',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/plants-11.jpg'
  },
  
  {
    id: 'seeds-0',
    name: 'Heirloom Rose Seeds',
    slug: 'heirloom-rose-seeds',
    shortDesc: 'Premium hand-picked Heirloom Rose Seeds directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Heirloom Rose Seeds. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'seeds',
    price: 199,
    discount: 16,
    rating: 4.5,
    reviews: 317,
    stock: 16,
    sku: 'SEE-4000',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: true,
    image: '/assets/products/seeds-0.jpg'
  },
  {
    id: 'seeds-1',
    name: 'Giant Sunflower Seeds',
    slug: 'giant-sunflower-seeds',
    shortDesc: 'Premium hand-picked Giant Sunflower Seeds directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Giant Sunflower Seeds. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'seeds',
    price: 431,
    discount: 0,
    rating: 4.5,
    reviews: 102,
    stock: 47,
    sku: 'SEE-4001',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: true,
    bestSeller: false,
    image: '/assets/products/seeds-1.jpg'
  },
  {
    id: 'seeds-2',
    name: 'English Lavender Seeds',
    slug: 'english-lavender-seeds',
    shortDesc: 'Premium hand-picked English Lavender Seeds directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke English Lavender Seeds. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'seeds',
    price: 369,
    discount: 0,
    rating: 4.9,
    reviews: 205,
    stock: 40,
    sku: 'SEE-4002',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/seeds-2.jpg'
  },
  {
    id: 'seeds-3',
    name: 'French Marigold Seeds',
    slug: 'french-marigold-seeds',
    shortDesc: 'Premium hand-picked French Marigold Seeds directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke French Marigold Seeds. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'seeds',
    price: 373,
    discount: 0,
    rating: 4.8,
    reviews: 98,
    stock: 42,
    sku: 'SEE-4003',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/seeds-3.jpg'
  },
  {
    id: 'seeds-4',
    name: 'Water Lotus Seeds',
    slug: 'water-lotus-seeds',
    shortDesc: 'Premium hand-picked Water Lotus Seeds directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Water Lotus Seeds. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'seeds',
    price: 1047,
    discount: 9,
    rating: 4.8,
    reviews: 94,
    stock: 22,
    sku: 'SEE-4004',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/seeds-4.jpg'
  },
  {
    id: 'seeds-5',
    name: 'Shasta Daisy Seeds',
    slug: 'shasta-daisy-seeds',
    shortDesc: 'Premium hand-picked Shasta Daisy Seeds directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Shasta Daisy Seeds. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'seeds',
    price: 1009,
    discount: 0,
    rating: 4.8,
    reviews: 123,
    stock: 42,
    sku: 'SEE-4005',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/seeds-5.jpg'
  },
  {
    id: 'seeds-6',
    name: 'Wildflower Cosmos Seeds',
    slug: 'wildflower-cosmos-seeds',
    shortDesc: 'Premium hand-picked Wildflower Cosmos Seeds directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Wildflower Cosmos Seeds. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'seeds',
    price: 811,
    discount: 0,
    rating: 4.6,
    reviews: 213,
    stock: 5,
    sku: 'SEE-4006',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/seeds-6.jpg'
  },
  {
    id: 'seeds-7',
    name: 'Dutch Tulip Bulbs',
    slug: 'dutch-tulip-bulbs',
    shortDesc: 'Premium hand-picked Dutch Tulip Bulbs directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Dutch Tulip Bulbs. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'seeds',
    price: 850,
    discount: 0,
    rating: 4.9,
    reviews: 305,
    stock: 10,
    sku: 'SEE-4007',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/seeds-7.jpg'
  },
  {
    id: 'seeds-8',
    name: 'Arabian Jasmine Seeds',
    slug: 'arabian-jasmine-seeds',
    shortDesc: 'Premium hand-picked Arabian Jasmine Seeds directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Arabian Jasmine Seeds. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'seeds',
    price: 1703,
    discount: 18,
    rating: 4.8,
    reviews: 137,
    stock: 40,
    sku: 'SEE-4008',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/seeds-8.jpg'
  },
  {
    id: 'seeds-9',
    name: 'Mixed Floral Seeds',
    slug: 'mixed-floral-seeds',
    shortDesc: 'Premium hand-picked Mixed Floral Seeds directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Mixed Floral Seeds. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'seeds',
    price: 1792,
    discount: 0,
    rating: 4.9,
    reviews: 231,
    stock: 5,
    sku: 'SEE-4009',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/seeds-9.jpg'
  },
  {
    id: 'seeds-10',
    name: 'Petunia Hybrid Seeds',
    slug: 'petunia-hybrid-seeds',
    shortDesc: 'Premium hand-picked Petunia Hybrid Seeds directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Petunia Hybrid Seeds. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'seeds',
    price: 2449,
    discount: 0,
    rating: 4.5,
    reviews: 220,
    stock: 52,
    sku: 'SEE-4010',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/seeds-10.jpg'
  },
  {
    id: 'seeds-11',
    name: 'Zinnia Elegans Seeds',
    slug: 'zinnia-elegans-seeds',
    shortDesc: 'Premium hand-picked Zinnia Elegans Seeds directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Zinnia Elegans Seeds. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'seeds',
    price: 1189,
    discount: 0,
    rating: 4.8,
    reviews: 53,
    stock: 53,
    sku: 'SEE-4011',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/seeds-11.jpg'
  },
  
  {
    id: 'decor-0',
    name: 'Silk Artisan Roses',
    slug: 'silk-artisan-roses',
    shortDesc: 'Premium hand-picked Silk Artisan Roses directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Silk Artisan Roses. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'decor',
    price: 1299,
    discount: 5,
    rating: 4.6,
    reviews: 276,
    stock: 41,
    sku: 'DEC-5000',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: true,
    image: '/assets/products/decor-0.jpg'
  },
  {
    id: 'decor-1',
    name: 'Faux Water Lotus',
    slug: 'faux-water-lotus',
    shortDesc: 'Premium hand-picked Faux Water Lotus directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Faux Water Lotus. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'decor',
    price: 1493,
    discount: 0,
    rating: 4.5,
    reviews: 160,
    stock: 45,
    sku: 'DEC-5001',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: true,
    bestSeller: false,
    image: '/assets/products/decor-1.jpg'
  },
  {
    id: 'decor-2',
    name: 'Festive Floral Garlands',
    slug: 'festive-floral-garlands',
    shortDesc: 'Premium hand-picked Festive Floral Garlands directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Festive Floral Garlands. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'decor',
    price: 1703,
    discount: 0,
    rating: 4.7,
    reviews: 298,
    stock: 29,
    sku: 'DEC-5002',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/decor-2.jpg'
  },
  {
    id: 'decor-3',
    name: 'Botanical Wall Decor',
    slug: 'botanical-wall-decor',
    shortDesc: 'Premium hand-picked Botanical Wall Decor directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Botanical Wall Decor. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'decor',
    price: 1902,
    discount: 0,
    rating: 5.0,
    reviews: 256,
    stock: 51,
    sku: 'DEC-5003',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/decor-3.jpg'
  },
  {
    id: 'decor-4',
    name: 'Luxury Table Centerpieces',
    slug: 'luxury-table-centerpieces',
    shortDesc: 'Premium hand-picked Luxury Table Centerpieces directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Luxury Table Centerpieces. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'decor',
    price: 2251,
    discount: 10,
    rating: 4.6,
    reviews: 241,
    stock: 38,
    sku: 'DEC-5004',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/decor-4.jpg'
  },
  {
    id: 'decor-5',
    name: 'Bridal Decor Flowers',
    slug: 'bridal-decor-flowers',
    shortDesc: 'Premium hand-picked Bridal Decor Flowers directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Bridal Decor Flowers. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'decor',
    price: 1619,
    discount: 0,
    rating: 4.9,
    reviews: 125,
    stock: 42,
    sku: 'DEC-5005',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/decor-5.jpg'
  },
  {
    id: 'decor-6',
    name: 'Cascading Hanging Flowers',
    slug: 'cascading-hanging-flowers',
    shortDesc: 'Premium hand-picked Cascading Hanging Flowers directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Cascading Hanging Flowers. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'decor',
    price: 2685,
    discount: 0,
    rating: 4.8,
    reviews: 320,
    stock: 32,
    sku: 'DEC-5006',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/decor-6.jpg'
  },
  {
    id: 'decor-7',
    name: 'Premium Vase Arrangements',
    slug: 'premium-vase-arrangements',
    shortDesc: 'Premium hand-picked Premium Vase Arrangements directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Premium Vase Arrangements. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'decor',
    price: 2230,
    discount: 0,
    rating: 5.0,
    reviews: 76,
    stock: 19,
    sku: 'DEC-5007',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/decor-7.jpg'
  },
  {
    id: 'decor-8',
    name: 'Minimalist Home Decor',
    slug: 'minimalist-home-decor',
    shortDesc: 'Premium hand-picked Minimalist Home Decor directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Minimalist Home Decor. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'decor',
    price: 3291,
    discount: 16,
    rating: 4.8,
    reviews: 333,
    stock: 51,
    sku: 'DEC-5008',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/decor-8.jpg'
  },
  {
    id: 'decor-9',
    name: 'Diwali Setup Decorations',
    slug: 'diwali-setup-decorations',
    shortDesc: 'Premium hand-picked Diwali Setup Decorations directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Diwali Setup Decorations. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'decor',
    price: 2631,
    discount: 0,
    rating: 4.7,
    reviews: 58,
    stock: 14,
    sku: 'DEC-5009',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/decor-9.jpg'
  },
  
  {
    id: 'gift-combos-0',
    name: 'Rose & Swiss Chocolate',
    slug: 'rose-&-swiss-chocolate',
    shortDesc: 'Premium hand-picked Rose & Swiss Chocolate directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Rose & Swiss Chocolate. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'gift-combos',
    price: 2999,
    discount: 15,
    rating: 4.6,
    reviews: 64,
    stock: 8,
    sku: 'GIF-6000',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: true,
    bestSeller: true,
    image: '/assets/products/gift-combos-0.jpg'
  },
  {
    id: 'gift-combos-1',
    name: 'Lily & Truffle Cake',
    slug: 'lily-&-truffle-cake',
    shortDesc: 'Premium hand-picked Lily & Truffle Cake directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Lily & Truffle Cake. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'gift-combos',
    price: 3212,
    discount: 0,
    rating: 5.0,
    reviews: 292,
    stock: 34,
    sku: 'GIF-6001',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: true,
    bestSeller: false,
    image: '/assets/products/gift-combos-1.jpg'
  },
  {
    id: 'gift-combos-2',
    name: 'Orchid & Signature Perfume',
    slug: 'orchid-&-signature-perfume',
    shortDesc: 'Premium hand-picked Orchid & Signature Perfume directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Orchid & Signature Perfume. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'gift-combos',
    price: 3333,
    discount: 0,
    rating: 4.9,
    reviews: 303,
    stock: 16,
    sku: 'GIF-6002',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/gift-combos-2.jpg'
  },
  {
    id: 'gift-combos-3',
    name: 'Tulip & Artisan Teddy',
    slug: 'tulip-&-artisan-teddy',
    shortDesc: 'Premium hand-picked Tulip & Artisan Teddy directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Tulip & Artisan Teddy. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'gift-combos',
    price: 3713,
    discount: 0,
    rating: 4.6,
    reviews: 133,
    stock: 23,
    sku: 'GIF-6003',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/gift-combos-3.jpg'
  },
  {
    id: 'gift-combos-4',
    name: 'Sunflower & Premium Wine',
    slug: 'sunflower-&-premium-wine',
    shortDesc: 'Premium hand-picked Sunflower & Premium Wine directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Sunflower & Premium Wine. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'gift-combos',
    price: 3639,
    discount: 9,
    rating: 4.6,
    reviews: 66,
    stock: 27,
    sku: 'GIF-6004',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/gift-combos-4.jpg'
  },
  {
    id: 'gift-combos-5',
    name: 'Floral & Himalayan Spa Set',
    slug: 'floral-&-himalayan-spa-set',
    shortDesc: 'Premium hand-picked Floral & Himalayan Spa Set directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Floral & Himalayan Spa Set. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'gift-combos',
    price: 4119,
    discount: 0,
    rating: 5.0,
    reviews: 275,
    stock: 14,
    sku: 'GIF-6005',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/gift-combos-5.jpg'
  },
  {
    id: 'gift-combos-6',
    name: 'Luxury Rose & Jewelry Box',
    slug: 'luxury-rose-&-jewelry-box',
    shortDesc: 'Premium hand-picked Luxury Rose & Jewelry Box directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Luxury Rose & Jewelry Box. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'gift-combos',
    price: 3947,
    discount: 0,
    rating: 5.0,
    reviews: 264,
    stock: 13,
    sku: 'GIF-6006',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/gift-combos-6.jpg'
  },
  {
    id: 'gift-combos-7',
    name: 'Carnation & Premium Sweets',
    slug: 'carnation-&-premium-sweets',
    shortDesc: 'Premium hand-picked Carnation & Premium Sweets directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Carnation & Premium Sweets. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'gift-combos',
    price: 4672,
    discount: 0,
    rating: 4.6,
    reviews: 267,
    stock: 41,
    sku: 'GIF-6007',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/gift-combos-7.jpg'
  },
  {
    id: 'gift-combos-8',
    name: 'Jasmine & Soy Candle Set',
    slug: 'jasmine-&-soy-candle-set',
    shortDesc: 'Premium hand-picked Jasmine & Soy Candle Set directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Jasmine & Soy Candle Set. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'gift-combos',
    price: 4583,
    discount: 13,
    rating: 5.0,
    reviews: 326,
    stock: 39,
    sku: 'GIF-6008',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: '2-3 Days',
    featured: false,
    bestSeller: false,
    image: '/assets/products/gift-combos-8.jpg'
  },
  {
    id: 'gift-combos-9',
    name: 'Ultimate Birthday Hamper',
    slug: 'ultimate-birthday-hamper',
    shortDesc: 'Premium hand-picked Ultimate Birthday Hamper directly from our luxury farms.',
    longDesc: 'Experience the pinnacle of floral luxury with our bespoke Ultimate Birthday Hamper. Cultivated in optimal microclimates, each product is meticulously selected to guarantee extraordinary beauty and elegance.',
    category: 'gift-combos',
    price: 5024,
    discount: 0,
    rating: 4.7,
    reviews: 303,
    stock: 28,
    sku: 'GIF-6009',
    flowerMeaning: 'Love, purity, and absolute perfection.',
    careInstructions: 'Keep in a cool, dry place. Handle with utmost care.',
    deliveryTime: 'Same Day Delivery',
    featured: false,
    bestSeller: true,
    image: '/assets/products/gift-combos-9.jpg'
  }
];

export const MOCK_USER = {
  name: 'Aarav Patel',
  email: 'aarav.patel@example.in',
  phone: '+91 98765 43210',
  memberSince: '2023',
  tier: 'Platinum Member',
  addresses: [
    { id: 1, type: 'Home', address: 'A-402, The Imperial Towers, Tardeo', city: 'Mumbai', state: 'Maharashtra', pin: '400034', isDefault: true },
    { id: 2, type: 'Office', address: 'Level 14, Cyber Hub, DLF Phase 2', city: 'Gurugram', state: 'Haryana', pin: '122002', isDefault: false }
  ]
};

export const MOCK_ORDERS = [
  { id: 'ORD-89234', date: '12 Oct 2025', total: 4299, items: 2, status: 'Delivered' },
  { id: 'ORD-89235', date: '28 Nov 2025', total: 1899, items: 1, status: 'Shipped' },
  { id: 'ORD-89236', date: '05 Jan 2026', total: 6499, items: 3, status: 'Pending' }
];

export const ADMIN_STATS = {
  revenue: '₹ 12,45,000',
  orders: 342,
  customers: 1205,
  conversion: '4.2%'
};
